### ISSUE TITLE
vgui_movie_display uses .bik presets

### ISSUE THREAD

**Issue by DarviL82** [ChaosInitiative/P2CE-FGD#1]
With *Smart Edit* on, when selecting our movie to display in the `Movie to display` keyvalue, the preset options will point to the respective `.bik `files, instead of the recently implemented `.webm` videos.

**Comment by braem** [comment]
Solved by https://github.com/ChaosInitiative/P2CE-FGD/commit/31d427fb244695dc899b5b9890cba72ca00a3e66? @SpyceTewan

**Comment by SpyceTewan** [comment]
Yup
